### ISSUE TITLE
IP Adress and other troubles

### ISSUE THREAD

**Issue by Sorcerer34** [icalmels/wordclock#2] opened 2023-10-21 12:46 UTC
Good morning.
I am trying to complete the configuration of my clock but the HTTP server is in the address range 192.168.4.1 
which does not correspond to my network address.
To avoid causing panic in my installation, it would be more practical for me if the clock was located in the 192.168.1.x 
address area but I have not yet found where this parameter can be modified.
A helping hand please???

Furthermore, I have not modified the code downloaded from the gitub, but I only have 15 LEDs that light up in width 
(compared to 16 in height) and I fear that this will cause me problems when my configuration is completed . 
What did I miss??

Thank you very much for any help.
Serge

**Comment by machintrucbidule** [comment] 2023-10-21 15:27
Hi Serge,

The issue isn't on the code side, but on your router. That's your router which is defining the ip address, not the clock.
(My router is also on the 192.168.1.x range, and all is working fine - and it would also work by default with a 10.0.0.x, 192.168.4.x range ... or anything else).

For the 15 width LED that's perfectly normal, no issue here. The letters matrix requires 13x14 leds. By adding the borders for seconds (top, right, bottom, left) it ends with a 15x16 matrix. One column isn't used, but as 15x16 led matrix aren't exising, I used a 16x16 one, with one column of leds kept blank.

**Comment by Sorcerer34** [comment] 2023-10-21 16:52
Good evening machintrucbidule...

I perfectly understood your explanation regarding the space of 15x16 LEDs needed for the display. We can also count on one of the images of the Github and we can see very clearly that in width there are only 15 LEDs lit. My mistake.

On the other hand, I don't quite understand your explanation regarding the router and IP addresses.
My router is in the 192.168.1.xx address range and I don't understand how the clock retrieves a 192.168.4.1 address?
Attached is an extract from the serial monitor:

"15:51:12.859 -> *wm:StartAP with SSID: clock
15:51:13.985 -> *wm:AP IP address: 192.168.4.1
15:51:13.985 -> Unable to connect on wifi - Entered wifi config mode
15:51:13.985 --> 192.168.4.1
15:51:13.985 -> clock
15:51:13.985 -> Display orange ring while wifi configuration
15:51:13.985 -> *wm:Starting Web Portal
"
I just re-checked my router configuration, there is no mention of the address range 192.168.4.xx
The sketch takes it from somewhere this address????
I must be missing something there...

Thank you so much.

**Comment by machintrucbidule** [comment] 2023-10-21 17:07
Ah, that's the first startup, when not yet connected on the wifi
Here the clock is seting up a new wifi network named "horloge". You have to connect on it (easier with a smartphone), then it will redirect you to the "web portal" where you'll be able to select your wifi network and enter credentials (and if not automatically redirecting to web portal, you can manually reach the 192.168.4.1 address from your web browser).
From here clock will restart, connect on your home wifi network, and will get an ip address from your router.
You also have a (too) short explanation on the "§6 Usage" of the readme.

That's the behaviour of the library "WiFiManager", which I used to be able to connect on any wifi network without having to change any configuration file. I can't change anything about it, but from my point of view that's working great as is (as soon you understand it creates a new wifi network 😁)

**Comment by Sorcerer34** [comment] 2023-10-21 18:00
Great great great .....
With the right method, it works better.
That's it, the configuration is complete and the clock displays the time.
Once again, thank you.
Friendships
Serge

**Comment by machintrucbidule** [comment] 2023-10-21 18:15
Welcome !

And now (if not already figured out) if you want to reach clock's configuration, you have to retrieve its ip address on your network (or on serial monitor) and put it on any web browser connected on the same network

**Comment by machintrucbidule** [comment] 2023-10-21 18:27
And by the way, I just pushed an update on the "functions.ino" file, for an old fix on color managment on a few situations, and which I had not committed

**Comment by machintrucbidule** [comment] 2023-10-21 18:28
And I close the issue

**Closed as completed by machintrucbidule** 2023-10-21 18:28 UTC
